### ISSUE TITLE
xpath expressions for title, authors, and pages are failing

### ISSUE THREAD

**Issue by nenock** [sbaltes/dblp-retriever#3]
Hi there! 
Unfortunately, I experienced a bunch of `WARNING: Empty page range for paper` which goes hand in hand with missing titles and authors in the output files. Here is what I have done:
- downloaded zip of master
- installed requirements
- run `python3 dblp-retriever.py -i input/venues.csv -o output/` (from the readme)

Therefore, the reason is that DBLP added a new class to the `cite` html element that contains the paper's meta data. Thus, the xpath expressions for title, authors, and pages with `cite[@class="data"]` return nothing.
I would suggest using `cite[contains(@class, "data")]` instead.

Running the dblp-retriever with the following lines worked on my machine:
`venue.py:58` `title = item.xpath('cite[contains(@class, "data")]/span[@itemprop="name"]/descendant-or-self::*/text()')`
`venue.py:64` `pages = item.xpath('cite[contains(@class, "data")]/span[@itemprop="pagination"]/text()')`
`venue.py:82` `authors = item.xpath('cite[contains(@class, "data")]/span[@itemprop="author"]/a/span[@itemprop="name"]/text()')`

Thanks for providing this tool, by the way!

**Comment by sbaltes** [comment]
Hi,
Thanks a lot for your feedback.
Would you mind creating a pull request for the proposed change?
I'd be happy to merge it.
I've not used the tool for a while and apparently DBLP changed their layout/structure, as you pointed out.
